name: tools21cm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - numpy=1.23.4
  - scipy=1.9.3
  - matplotlib=3.6.2
  - pytest=7.2.0
  - pip
  - pip:
    - -r requirements.txt  # This ensures any additional pip packages are installed
